google_bucket_name = "adnan-fuchicorp"
deployment_name = "common_tools"
google_project_id = "fuchicorp-288907"
google_domain_name = "bugdalorian.com"
credentials = "common-service-account.json"
deployment_environment = "dev"
